ecommersApp/urls.py
from django.urls import path
from ecommersApp.views import index, products_list_view,category_list_view,category_product_list_view


app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("products/", products_list_view, name="product-list"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

]

ecommersProject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecommersApp.urls")),
    path("user/", include("userauths.urls")),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
]

templates/core/category_list_view.html
{% extends "index.html" %}
{% load static%}
{% block content%}
    <section class="w3l-witemshny-main py-5">
        <div class="container py-md-4">
            <h3 class="title-w3l mt-5 pt-lg-4">{{categories.count}} Categories</h3>

            <!--/row-1-->
            <div class="witemshny-grids row mt-lg-3">
                {% for c in categories  %}
                <div class="col-xl-2 col-md-4 col-6 product-incfhny mt-4">

                    <div class="weitemshny-grid oposition-relative">
                        <a href="{% url 'core:category-product-list' %}" class="d-block zoom"><img src="{{ c.image.url }}" alt="" class="img-fluid news-image"></a>
                        <div class="witemshny-inf">
                        </div>
                    </div>
                    <h4 class="gdnhy-1 mt-4"><a href="products-1.html">{{ c.title }} </a>
                    </h4>
                    <div>
                        <span>{{ c.category.count}} Product{{ c.category.count|pluralize}}</sapn>
                    </div>
                </div>
                {% endfor %}
            </div> 
        </div>
    </selection> 
                        

{% endblock content %}