ecommersProject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecommersApp.urls")),
    path("user/", include("userauths.urls")),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True, null=False)
    username = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']


    def __str__(self):
        return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput (attrs={"placeholder":"Confirm Password"}))

    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User

#User = settings.AUTH_USER_MODEL

def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, Your account was created successfully")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect("core:index") 
    else:
        form = UserRegisterForm()

    context = {
        'form' : form,
    }
    
    return render(request, "userauths/sign-up.html", context)


def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey you are already Logged In.")
        return redirect("core:index")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request,"You are logged in")
                return redirect("core:index")
        
            else:
                 messages.warning(request, "User Does Not Exist, Create an account.")
        except:
            messages.warning(request, f"User with {email} does not exist")

    return render(request, "userauths/sign-in.html")




def logout_view(request):
    logout(request)
    messages.warning(request, "You logged out.")
    return redirect("userauths:sign-in")

templates/userauths/sign-in.html
{% extends "index.html" %}
{% load static%}
{% block content%}
    <section class="w3mid-gap"></section>
    <!--/Banner-Start-->
    <!--/inner-page-->
    <div class="inner-banner py-5">
        <section class="w3l-breadcrumb text-left py-sm-5 ">
            <div class="container">
                <div class="w3breadcrumb-gids">
                    <div class="w3breadcrumb-left text-left">
                        <h2 class="inner-w3-title">
                            Login </h2>
                    </div>
                    <div class="w3breadcrumb-right">
                        <ul class="breadcrumbs-custom-path">
                            <li><a href="index.html">Home</a></li>
                            <li class="active"><span class="fas fa-angle-double-right mx-2"></span> Login </li>
                        </ul>
                    </div>
                </div>

            </div>
        </section>
    </div>
    <!--//inner-page-->
	<div style="margin: 8px auto; display: block; text-align:center;">
        <div style="margin: 8px auto; display: block; text-align:center;">
            

<!---728x90--->

 
</div>
    <section class="w3l-forml-main py-5">
        <div class="form-hnyv-sec py-sm-5 py-3">
            <!--form-stars-here-->
            <div class="form-wrapv">

                <h2>Login to your account</h2>
                <form action="" method= "post" method="POST">
                    {% csrf_token %}
                    <div class="form-sub-w3">
                        <input type="text" required name="email" placeholder="Email " />
                        <div class="icon-w3">
                            <span class="fas fa-user" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="form-sub-w3">
                        <input required type="password" name="password" placeholder="Your Password " />
                        <div class="icon-w3">
                            <span class="fas fa-unlock-alt" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="form-sub-content">
                        <p class="forgot-w3ls">Forgot Password?<a class href="#"> Click here</a></p>
                        <p class="forgot-w3ls1">New User? <a class href="{% url 'userauths:sign-up' %}">Signup here</a></p>
                    </div>
                    <div class="submit-button text-center">
                        <button type="submit" class="btn btn-style btn-primary">Login Now</button>

                    </div>
                </form>

            </div>
            <!--//form-ends-here-->
        </div>
        <!-- //coming -->
    </section>
	
        

<!---728x90
 
</div>-->
{% endblock content%}

templates/userauths/sign-up.html
{% extends "index.html" %}
{% load static%}
{% block content%}
    <section class="w3mid-gap"></section>
    <!--/Banner-Start-->
    <!--/inner-page-->
    <div class="inner-banner py-5">
        <section class="w3l-breadcrumb text-left py-sm-5 ">
            <div class="container">
                <div class="w3breadcrumb-gids">
                    <div class="w3breadcrumb-left text-left">
                        <h2 class="inner-w3-title">
                            Signup </h2>
                    </div>
                    <div class="w3breadcrumb-right">
                        <ul class="breadcrumbs-custom-path">
                            <li><a href="index.html">Home</a></li>
                            <li class="active"><span class="fas fa-angle-double-right mx-2"></span> Signup </li>
                        </ul>
                    </div>
                </div>

            </div>
        </section>
    </div>
    <!--//inner-page-->
	<div style="margin: 8px auto; display: block; text-align:center;">
        {%if form.errors %}
        <div class="form-wrapv">
            
            <strong>{{form.errors}}          <i class="fa-solid fa-bug" style="color: #c91313;"></i></strong>
            
        </div>
        {% endif %}

<!---728x90--->

 
</div>
    <section class="w3l-forml-main py-5">
        <div class="form-hnyv-sec py-sm-5 py-3">
            <!--form-stars-here-->
            
            <div class="form-wrapv">

                <h2>Create an Account</h2>
                <form action="" method="post" method="POST">

                    {% csrf_token %}
                    <div class="form-sub-w3">
                        {{form.username}}
                        <div class="icon-w3">
                            <span class="fas fa-user" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="form-sub-w3">
                        {{form.email}}
                        <div class="icon-w3">
                            <span class="" aria-hidden="true"><i class="fa-solid fa-envelope"></i></span>
                        </div>
                    </div>
                    <div class="form-sub-w3">
                        {{form.password1}}
                        <div class="icon-w3">
                            <span class="" aria-hidden="true"><i class="fa-solid fa-lock"></i></span>
                        </div>
                    </div>
                    <div class="form-sub-w3">
                        {{form.password2}}
                        <div class="icon-w3">
                            <span class="" aria-hidden="true"><i class="fa-solid fa-key"></i></span>
                        </div>
                    </div>
                    <!--<div class="form-sub-w3">
                        <input type="text" name="Username" placeholder="Username " required="" />
                        <div class="icon-w3">
                            <span class="fas fa-user" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="form-sub-w3">
                        <input type="password" name="Password" placeholder="Password" required="" />
                        <div class="icon-w3">
                            <span class="fas fa-unlock-alt" aria-hidden="true"></span>
                        </div>
                    </div>-->
                    <div class="">
                        <p class="forgot-w3ls">Already have an account?<a class href="{% url 'userauths:sign-in' %}"> Login</a></p>
                    </div>
                    <div class="submit-button text-center">
                        <button type="submit" class="btn btn-style btn-primary">Submit & Register </button>

                    </div> 
                </form>

            </div>
            <!--//form-ends-here-->
        </div>
        <!-- //coming -->
    </section>
	<div style="margin: 8px auto; display: block; text-align:center;">
    </div>

    
{% endblock content%}